parameters:
#    cg_manage.example.class: CG\ManageBundle\Example

services:
#    cg_manage.example:
#        class: %cg_manage.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
